train_file: ['../../data/VisWis_VQA_Grounding/annotations/train_grounding.json']
             
test_file: ['../../data/VisWis_VQA_Grounding/annotations/val_grounding.json']
test_file2: ['../../data/VisWis_VQA_Grounding/annotations/test_grounding.json']
answer_list: '../../processed/answer_list.json'

vqa_root: {'train': '../../processed/masked', 'test': '../../data/VisWis_VQA_Grounding/val', 'test2': '../../data/VisWis_VQA_Grounding/test'}
# vg_root: '/export/share/datasets/vision/visual-genome/'  #image/
#'train': '../../data/VisWis_VQA_Grounding/train'
image_res: 384
batch_size_train:   16
batch_size_test: 1
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







